### ISSUE TITLE
Where to output the CSV file

### ISSUE THREAD

**Issue by patrickmorrell17** [cafltar/plfa_tools_aggregator#10]
Hey Bryan,

I was just wondering if there is a specific place where you would want the CSV file to be output to from the main function?

**Comment by bryanrcarlson** [comment]
If users run the module from the command line, have them pass the output path as an argument. You'll need to use `from sys import argv` then unpack it in the script: `script, output_path = argv`

**Comment by patrickmorrell17** [comment]
Ok, will do! Thanks!
