### ISSUE TITLE
Trouble with __main__.py script

### ISSUE THREAD

**Issue by patrickmorrell17** [cafltar/plfa_tools_aggregator#11]
I believe I am close to having this script done, but for some reason when it calls the read dir function it says the system cannot find the path specified. Also, I believe I found an error in my read dir function--it should be a simple fix. I am assuming I should push my current branch and switch over to the read_dir branch to fix this though. I am going to go ahead and push my branch so you can take a look.

**Comment by patrickmorrell17** [comment]
The problem is occurring at the 
for filename in os.listdir(dir_path):
line (line 114)

**Comment by bryanrcarlson** [comment]
Code looks okay to me. Try adding a print function to output `dir_path` before the for loop in the `read_dir` function. Could be issue with command line argument not being specified correctly?

**Comment by patrickmorrell17** [comment]
Ok, I will try that out. I am going to fix the read_dir function first and then I'll continue to tinker with the main.py!
