### ISSUE TITLE
Got __main__.py working ... may be some refactoring to do 

### ISSUE THREAD

**Issue by patrickmorrell17** [cafltar/plfa_tools_aggregator#15]
Hey Bryan,

Good news, I got the main.py script to work! I think it was the error I saw in the read_dir function that was giving me trouble. I feel like most of the examples I have seen online have a main function defined inside of the main.py file with:
```
if __name__ == "__main__":
     main()
```
at the bottom (you have probably seen I have it commented out in the current pr), which I do not currently. I may go back and change this so it is more in line with some of the ones I see online.

**Comment by bryanrcarlson** [comment]
Hi Patrick -- the code block you referenced is so the script can be imported without all the code running. `__name__` is a python reserved var that indicates the calling module. So if the file is run at the command line `python myfile.py`, then __name__ will equal "__main__". It's something else if it's called within another file (using import).
