### ISSUE TITLE
Format docstrings to be compatible with Pydoc

### ISSUE THREAD

**Issue by bryanrcarlson** [cafltar/plfa_tools_aggregator#16]
Current docstrings do not take advantage of pydoc formatting. For example:

```
def transform_raw_to_stacked(self, plfa_tools_output: pd.DataFrame) -> pd.DataFrame:
        """Reformats output from PLFA Tools, of a single sample, into proper tabular format
        plfa_tools_output = Output from PLFA Tools of a single worksheet in the form of a Pandas DataFrame
        
        Header names: SampleId, GCRunId, GCFileLoc, ProcessingCode, ProcessMethod, RunDateTime, RT, Response, Ar/Ht, RFact, ECL, Peak Name, Percent, Comment1, Comment2
        """
```

Should be:

```
def transform_raw_to_stacked(self, plfa_tools_output: pd.DataFrame) -> pd.DataFrame:
        """Reformats output from PLFA Tools, of a single sample, into proper tabular format
        :param plfa_tools_output: Output from PLFA Tools of a single worksheet in the form of a Pandas DataFrame
        
        :return: DataFrame. Header names: SampleId, GCRunId, GCFileLoc, ProcessingCode, ProcessMethod, RunDateTime, RT, Response, Ar/Ht, RFact, ECL, Peak Name, Percent, Comment1, Comment2
        """
```

See: https://saddlebackcss.github.io/tutorials/python/basic/2016/01/14/python-basics-4

**Comment by patrickmorrell17** [comment]
You will want to look at the docstring I added for the general Aggregator class. I did not find too many examples online of what the proper structure for this is so I followed this one:
[](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)
This seems to be slightly outdated and also I am not sure if the functions in our class would be considered attributes.

**Comment by patrickmorrell17** [comment]
It looks like the link I added didn't post. Here it is:
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by bryanrcarlson** [comment]
I think I'm finally understanding all of this. It turns out the old docstrings I wrote were in Google Style format, and that is what you wrote for the Aggregator class. What I proposed above was in 
 reStructuredText format. I believe reStructuredText (reST) is more "standard" but is more complex. For what we're doing, let's stay with reST. 

Finding good examples was hard because reST is used for other things than python docs. But here's one good resource: https://cheat.readthedocs.io/en/latest/rst.html

I'll try to get Sphinx set up and see what the actual output looks like. Hopefully I'll do this tomorrow.

The PR you created is very close. I think we still need to specify the parameter types (`:type [parameter name]:`) and return types (`:rtype:`). I'll make comments on PR.

Great job linking the PR and Issue, by the way.

**Comment by bryanrcarlson** [comment]
I spent some time this morning to actually generate the docs using Sphinx. I hit a few hurdles, but was able to generate some html. 

Here it is at current state:

![image](https://user-images.githubusercontent.com/12533203/74470777-fc473a80-4e53-11ea-9b35-ef95485a7677.png)

Pretty snazzy! 

These resources were helpful:
* https://sphinx-rtd-tutorial.readthedocs.io/en/latest/index.html
* https://shunsvineyard.info/2019/09/19/use-sphinx-for-python-documentation/

**Comment by patrickmorrell17** [comment]
Wow, that looks good! I am going to try that out as well after I make the changes reST format. I will let you know when I re-push the documentation branch with the correct changes.

**Comment by bryanrcarlson** [comment]
When you're ready to use Sphinx, I suggest you copy/paste the project folder and do a test run there first. I had to restart a couple of times.

Some gotchas:
* On Windows, if you're using conda, I was able to install Sphinx with `conda install sphinx`
* Make sure the "docs" folder the cwd before running `sphinx-quickstart`
* During `sphinx-quickstart` options: 
  * separate source and ubild directies: Y
  * Authors: "Patrick Morrell, Bryan Carlson"
  * Project release: "0.1.0"
  * language [en]: <press enter for default>
* You don't need to specify an extension in conf.py to process ReST format, but you do need to include `'sphinx.ext.autodoc'` or you'll get an error while generating docs.
* I think you can just create a `requirements.txt` file at root (one reference suggested you pip install requirements.txt)

Good luck!

**Comment by patrickmorrell17** [comment]
I believe I made the correct changes to the PR. I am having some issues using sphinx that I will have to continue troubleshooting, so I was not able to preview it.
