### ISSUE TITLE
Updating the README.md

### ISSUE THREAD

**Issue by patrickmorrell17** [cafltar/plfa_tools_aggregator#20]

**Comment by patrickmorrell17** [comment]
@bryanrcarlson  Do you think I should use markdown for the README or should I use reStructuredText? I am seeing that reStructuredText is common with python projects.

**Comment by bryanrcarlson** [comment]
I believe I read the markdown is supported now. I say go with Markdown since it's more common outside python and much simpler than reStructuredText

**Comment by patrickmorrell17** [comment]
@bryanrcarlson  OK, do you think you could repost that link to the test upload you did to PyPi? I ask because I want to put everything that is included in the package in the README.

**Comment by patrickmorrell17** [comment]
@bryanrcarlson nevermind, I was able to find the old one you posted

**Comment by patrickmorrell17** [comment]
I just pushed what I have for the README and created a pr #22. I am sure there are some things I am missing. If there is anything I need to add just let me know.

**Comment by bryanrcarlson** [comment]
@patrickmorrell17 Looks good. 

If you want to flesh it out more, we could add some example code under Installation information (```pip install plfatools```) and under "Using this package"? Maybe provide guidance and example code for use from the command line (as you've done) and as an imported library.

**Comment by patrickmorrell17** [comment]
@bryanrcarlson Ok, I will make these changes and re-push the branch.

**Comment by patrickmorrell17** [comment]
I tried to flesh out the README a bit more (added some example code etc) in or #22 . Let me know if there's anything else you want me to add! Apologies for taking so long to get this done, last few weeks have been a bit hectic.

**Comment by bryanrcarlson** [comment]
@patrickmorrell17 , looks good! 

No problem with delay. Whether or not it's related, a pandemic is a good excuse for everything.
