### ISSUE TITLE
Prepare code for publication to PyPI

### ISSUE THREAD

**Issue by bryanrcarlson** [cafltar/plfa_tools_aggregator#5]
* Remove any print statements
* Clean up code outside of classes (I think test module is only one with this?)
* Edit \_\_init\_\_.py to include proper import statement (from plfatools.aggregator import Aggregator)
* Add setup.py, setup.cfg files
  * See: https://gist.github.com/joelbarmettlerUZH/3e9d941b02107ecd558eca82445a923e#file-setup-py
  * Will need to tag a release version in github
  * install_requires = ['pathlib', 'pandas', 'numpy']
* Refine LICENSE and README files (rename LICENSE.md to LICENSE.txt?)
* Look into standard documentation? See: https://realpython.com/documenting-python-code/#documenting-your-python-code-base-using-docstrings

## References
* https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56
* https://realpython.com/pypi-publish-python-package/  <- this one seems more current

**Comment by bryanrcarlson** [comment]
\_\_ini\_\_ file should have \_\_version\_\_ = "0.1.0"

**Comment by bryanrcarlson** [comment]
Consider creating a \_\_main\_\_.py file so the module can be run from interpreter with path to file or folder as command line argument.

See: Different Ways of Calling a Package in https://realpython.com/pypi-publish-python-package/

**Comment by bryanrcarlson** [comment]
Reviewed: https://realpython.com/pypi-publish-python-package/. Here are hanging tasks. We may create new issues from them or just consider them part of this mega-issue:

* Move `__main__.py` into `plfatools` folder (allows `$ python -m plfatools 'folderpath'`)
	* As a best practice, use `if __name__ == "__main__": main()`, and wrap current logic in `def main():`
* `setup.py`
	* Use setuptools instead of distutils (`from setuptools import setup`)
	* specify `entry_points = {"console_scripts": ["plfatools=plfatools.__main__:main"]}`
	* Include `long_description` and `long_description_content_type = 'text/markdown'`
	* Replace classifiers = [...] with (see: https://pypi.org/classifiers/):
```
                 classifiers=[
			'Development Status :: 4 - Beta',     
			'Intended Audience :: Science/Research',      
			'Topic :: Scientific/Engineering',
			'Topic :: Scientific/Engineering :: Bio-Informatics',
			'License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication',  
			'Programming Language :: Python :: 3'
		  ]
```
	* Read in `README.md` and set it as `long_description`
* Flesh out `README.md` with installation, example uses, etc. (probably new issue)
* Probably delete setup.cfg

Also, to better understand this process, I published current version (with some minor changes) to test.pypi: https://test.pypi.org/project/plfatools/0.1.0

**Comment by patrickmorrell17** [comment]
OK - I'll make these changes as soon as possible- I have midterms in all my classes this week so I may not get to it until the weekend. I will keep you updated!

**Comment by patrickmorrell17** [comment]
I fixed everything regarding the main.py file. One note: now when I try to test it from the command line, I have to run the command line as administrator for it to work. If I don't do this it won't import the pandas/numpy modules. I believe this is just something to do with how I installed the modules.

**Comment by patrickmorrell17** [comment]
One problem we will need to fix is deleting the old __main__.py file and setup.cfg file from the master branch since I believe I do not have permission to edit the master branch.

**Comment by bryanrcarlson** [comment]
@patrickmorrell17 , I think that's a good guess on admin issue. 

What are you next steps? Are you planning on tackling changes to setup.py?

I think we're getting close!

**Comment by patrickmorrell17** [comment]
@bryanrcarlson I have just finished the setup.py if you want to look over my most recent pr #19   Also in case, you didn't see my earlier comment, you are going to need to delete the old __main__.py and setup.cfg, as I can not delete things from the master branch. I just need to work on the readme.md and we should be done after that! I am going to go ahead and create a new issue for that!

**Comment by bryanrcarlson** [comment]
@patrickmorrell17 Great! After you create a PR for the changes to readme, I'll do a cleanup sweep and check that everything is good for submitting to test.pypi. Once we're happy with whats on pypi I'll tag the commit and we're golden!
