### ISSUE TITLE
Going to get started on standard documentation / command line capabilities next

### ISSUE THREAD

**Issue by patrickmorrell17** [cafltar/plfa_tools_aggregator#8]
I finished up making the changes to the setup.py file. The standard documentation does not look too complicated so I think I will go ahead and add that in as well. After that, I will get started on the command line functions for the package!

**Comment by bryanrcarlson** [comment]
If it's not too much work, go ahead and push the documentation code to your current pull request. Let's make a new branch/pull request for command line function.

Thanks!

**Comment by patrickmorrell17** [comment]
I actually have not started on the standard documentation yet, I was going to work on the command line function first. I already did make a new branch for the command line function though!

**Comment by bryanrcarlson** [comment]
That's great. I'll merge the current PR then.
